# Generated by Django 6.0.4 on 2026-04-09 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankImportSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parser_key', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategorizationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=100)),
                ('match_type', models.CharField(choices=[('REGEX', 'Regex'), ('CONTAINS', 'Contains'), ('AMOUNT_RANGE', 'Amount range')], max_length=20)),
                ('pattern', models.CharField(max_length=255)),
                ('vendor_name', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorization_rules', to='expenses.expensecategory')),
            ],
            options={
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='expenses.bankimportsource')),
            ],
            options={
                'ordering': ['-imported_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ImportedBankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posted_on', models.DateField()),
                ('description_raw', models.CharField(max_length=255)),
                ('amount_cents', models.IntegerField()),
                ('direction', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=10)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('external_hash', models.CharField(max_length=255, unique=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_transactions', to='expenses.expense')),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expenses.expenseimportbatch')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='expenses.bankimportsource')),
            ],
            options={
                'ordering': ['-posted_on', '-id'],
            },
        ),
    ]
