# Generated by Django 6.0.4 on 2026-04-09 04:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_cents', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('ISSUED', 'Issued'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('VOID', 'Void'), ('OVERDUE', 'Overdue')], default='ISSUED', max_length=20)),
                ('service_period_start', models.DateField(blank=True, null=True)),
                ('service_period_end', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('total_cents', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['due_date', 'issue_date', 'invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('DUES', 'Dues'), ('DONATION', 'Donation'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('amount_cents', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='MemberBalanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('credit_cents', models.IntegerField()),
                ('receivable_cents', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-as_of', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_cents', models.PositiveIntegerField()),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('source_type', models.CharField(choices=[('DUES_PAYMENT', 'Dues payment'), ('PREPAYMENT_TOPUP', 'Prepayment top-up'), ('ARREARS_CATCHUP', 'Arrears catch-up'), ('DONATION', 'Donation'), ('OTHER_INCOME', 'Other income')], max_length=30)),
                ('processor', models.CharField(blank=True, choices=[('STRIPE', 'Stripe'), ('SQUARE', 'Square'), ('BRAINTREE', 'Braintree'), ('HELCIM', 'Helcim'), ('AUTHORIZE_NET', 'Authorize.Net')], max_length=20, null=True)),
                ('processor_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('processor_balance_txn_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-received_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessorCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(choices=[('STRIPE', 'Stripe'), ('SQUARE', 'Square'), ('BRAINTREE', 'Braintree'), ('HELCIM', 'Helcim'), ('AUTHORIZE_NET', 'Authorize.Net')], max_length=20)),
                ('processor_customer_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['processor', 'processor_customer_id'],
            },
        ),
        migrations.CreateModel(
            name='ProcessorPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(choices=[('STRIPE', 'Stripe'), ('SQUARE', 'Square'), ('BRAINTREE', 'Braintree'), ('HELCIM', 'Helcim'), ('AUTHORIZE_NET', 'Authorize.Net')], max_length=20)),
                ('processor_payment_method_id', models.CharField(max_length=255)),
                ('method_type', models.CharField(choices=[('card', 'Card'), ('ach', 'ACH'), ('wallet', 'Wallet')], max_length=20)),
                ('fingerprint_hash', models.CharField(blank=True, max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor', models.CharField(choices=[('STRIPE', 'Stripe'), ('SQUARE', 'Square'), ('BRAINTREE', 'Braintree'), ('HELCIM', 'Helcim'), ('AUTHORIZE_NET', 'Authorize.Net')], max_length=20)),
                ('event_id', models.CharField(max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload_json', models.JSONField(default=dict)),
                ('signature_valid', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at', 'id'],
            },
        ),
    ]
