# Generated by Django 6.0.4 on 2026-04-09 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='members.client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='members.member'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='billing.invoice'),
        ),
        migrations.AddField(
            model_name='memberbalancesnapshot',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_snapshots', to='members.member'),
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='members.client'),
        ),
        migrations.AddField(
            model_name='payment',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='members.member'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='billing.payment'),
        ),
        migrations.AddField(
            model_name='processorcustomer',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor_customers', to='members.client'),
        ),
        migrations.AddField(
            model_name='processorpaymentmethod',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor_payment_methods', to='members.client'),
        ),
        migrations.AddField(
            model_name='processorpaymentmethod',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='members.member'),
        ),
        migrations.AddConstraint(
            model_name='webhookevent',
            constraint=models.UniqueConstraint(fields=('processor', 'event_id'), name='uniq_webhook_processor_event_id'),
        ),
        migrations.AddConstraint(
            model_name='memberbalancesnapshot',
            constraint=models.UniqueConstraint(fields=('member', 'as_of'), name='uniq_member_balance_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('processor__isnull', False), ('processor_payment_id__isnull', False)), fields=('processor', 'processor_payment_id'), name='uniq_processor_payment_id'),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_cents__gt', 0)), name='allocation_positive_cents'),
        ),
        migrations.AddConstraint(
            model_name='processorcustomer',
            constraint=models.UniqueConstraint(fields=('processor', 'processor_customer_id'), name='uniq_processor_customer_external_id'),
        ),
        migrations.AddConstraint(
            model_name='processorpaymentmethod',
            constraint=models.UniqueConstraint(fields=('processor', 'processor_payment_method_id'), name='uniq_processor_payment_method_external_id'),
        ),
    ]
