# Generated by Django 6.0.4 on 2026-04-09 05:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
        ('members', '0002_client_client_type_client_display_name_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='allocation',
            options={'ordering': ['allocated_at', 'id']},
        ),
        migrations.AddField(
            model_name='allocation',
            name='allocated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='allocation',
            name='invoice_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='billing.invoiceline'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_processor',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('EVERYORG', 'Every.org'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('MEMBER_DUES', 'Member dues'), ('RECURRING_AD_HOC', 'Recurring ad-hoc'), ('ONE_OFF', 'One-off')], default='ONE_OFF', max_length=30),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='line_total_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='service_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='service_period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='unit_price_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE_CARD', 'Stripe card'), ('STRIPE_ACH', 'Stripe ACH'), ('CASH', 'Cash'), ('CHECK', 'Check'), ('BANK_TRANSFER', 'Bank transfer'), ('EVERYORG', 'Every.org'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='payment',
            name='processor_charge_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='processor_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PARTIALLY_PAID', 'Partially paid'), ('PAID', 'Paid'), ('VOID', 'Void'), ('OVERDUE', 'Overdue')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='amount_cents',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='line_type',
            field=models.CharField(choices=[('DUES', 'Dues'), ('TOOL_FEE', 'Tool fee'), ('ROOM_FEE', 'Room fee'), ('SUPPLY', 'Supply'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='income_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='billing.incomecategory'),
        ),
        migrations.CreateModel(
            name='InvoiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_type', models.CharField(choices=[('MEMBER_DUES', 'Member dues'), ('RECURRING_AD_HOC', 'Recurring ad-hoc'), ('ONE_OFF', 'One-off')], default='ONE_OFF', max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('frequency', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ANNUAL', 'Annual'), ('ONE_OFF', 'One-off')], default='MONTHLY', max_length=20)),
                ('generation_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('due_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('due_offset_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('last_issued_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_schedules', to='members.client')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_schedules', to='members.member')),
            ],
            options={
                'ordering': ['client_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MemberCreditLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('PAYMENT_IN', 'Payment in'), ('CHARGE_OUT', 'Charge out'), ('MANUAL_ADJUSTMENT', 'Manual adjustment'), ('REVERSAL', 'Reversal')], max_length=30)),
                ('delta_cents', models.IntegerField()),
                ('effective_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ledger_entries', to='members.member')),
            ],
            options={
                'ordering': ['effective_at', 'id'],
            },
        ),
    ]
