# Generated by Django 6.0.4 on 2026-04-09 04:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('organization_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address_line_1', models.CharField(blank=True, max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'organization_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_class', models.CharField(choices=[('FULL', 'Full'), ('HARDSHIP', 'Hardship')], default='FULL', max_length=20)),
                ('status', models.CharField(choices=[('APPLICANT', 'Applicant'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past due'), ('SUSPENDED', 'Suspended'), ('LEFT', 'Left')], default='APPLICANT', max_length=20)),
                ('joined_at', models.DateField(default=django.utils.timezone.now)),
                ('left_at', models.DateField(blank=True, null=True)),
                ('dues_override_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('autopay_enabled', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autopay_payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autopay_members', to='billing.processorpaymentmethod')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='members.client')),
            ],
            options={
                'ordering': ['client__last_name', 'client__first_name', 'id'],
            },
        ),
    ]
