# Generated by Django 6.0.4 on 2026-04-09 04:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('PERSON', 'Person'), ('ORGANIZATION', 'Organization')], default='PERSON', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='display_name_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='legal_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='default_payment_method_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='door_access_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='member_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='member',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='member',
            name='voting_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ClientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_type', models.CharField(choices=[('NAME', 'Name'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('ADDRESS', 'Address')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='members.client')),
            ],
            options={
                'ordering': ['-valid_from', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('membership_class', models.CharField(choices=[('FULL', 'Full'), ('HARDSHIP', 'Hardship')], max_length=20)),
                ('monthly_dues_cents', models.PositiveIntegerField()),
                ('voting_eligible', models.BooleanField(default=True)),
                ('door_access_enabled', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_terms', to='members.member')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
    ]
