# Generated by Django 6.0.4 on 2026-04-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAllowlistSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etag', models.CharField(max_length=64, unique=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('payload_json', models.JSONField(default=dict)),
                ('signature', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-generated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('credential_uid', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=50)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RFIDCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uid'],
            },
        ),
    ]
