# Generated by Django 6.0.4 on 2026-04-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_charge_id', models.CharField(max_length=255, unique=True)),
                ('donor_name', models.CharField(blank=True, max_length=255)),
                ('donor_email', models.EmailField(blank=True, max_length=254)),
                ('amount_cents', models.PositiveIntegerField()),
                ('net_amount_cents', models.PositiveIntegerField(blank=True, null=True)),
                ('currency', models.CharField(default='usd', max_length=10)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('donation_date', models.DateTimeField()),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('partner_metadata', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-donation_date', '-id'],
            },
        ),
    ]
